### ISSUE TITLE
How to read the DB?

### ISSUE THREAD

**Issue by EhRabz** [dtzxporter/hd2-name-db#3]
No idea what a .pndb is. How can we see the DB?

**Comment by EhRabz** [comment]
Also would be much easier to just pin an issue with the main thread , and have people comment what they discover, and add that to the main thread no?

**Comment by dtzxporter** [comment]
The raw database is in assets.txt.

The releases section has a generated database for use with Diver.

**Comment by dtzxporter** [comment]
Anyone can create an issue and add names and someone will take care of a PR.

**Comment by dtzxporter** [comment]
I'm gonna close this, you can open an issue with hashes if you have them, the latest text database is here: https://github.com/dtzxporter/hd2-name-db/blob/main/assets.txt
